[package]
name = "rust-analyzer-issue3667"
version = "0.1.0"
authors = ["Denny Britz <dennybritz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mylib"
path = "src/lib.rs"

[dependencies]
